name: Sync Fork Upstream
on:
  schedule:
    - cron: '0 0 * * 1' # UTC时间，每天早8点执行，可自行修改
  workflow_dispatch: # 允许手动点击 Run workflow 触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh repo sync ${{ github.repository }} --branch main
